### ISSUE TITLE
Fix: Change name from read to scan

### ISSUE THREAD

**Issue by KSSaiTeja** [KSCHarika/QR-Scanner#3]
On the home screen the it would be better if it looks like below image..

| Suggested one                     | Present one                      |
| ----------------------------------- | ----------------------------------- |
| ![Screenshot 1](https://github.com/KSCHarika/QR-Scanner/assets/130981122/d29764f9-1ec0-4d63-bb04-09051a80a4d9)     | ![Screenshot 2](https://github.com/KSCHarika/QR-Scanner/assets/130981122/7573cf2e-85b0-4b90-afdd-4c4db4483ab8)     |

**Comment by KSCHarika** [comment]
@KSSaiTeja Thanks for raising this issue. I will assign you.. Go ahead!!

**Comment by KSSaiTeja** [comment]
@KSCHarika Thanks for assigning.. I will start work and raise a PR..

**Comment by KSCHarika** [comment]
i am closing this issue as it already completed
